# Generated by Django 5.0 on 2023-12-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_type_task_task_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_types',
        ),
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(related_name='tasks', to='webapp.type', verbose_name='Типы'),
        ),
    ]
