# Generated by Django 5.0 on 2023-12-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_project_alter_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.project', verbose_name='Проект'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='status',
            table='statuses',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
        migrations.AlterModelTable(
            name='type',
            table='types',
        ),
    ]
