# Generated by Django 5.0 on 2024-01-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_users_in_project', 'Добавить юзеров в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
